services:
  - type: web
    name: tomato-frontend
    env: static
    buildCommand: npm run build
    startCommand: npm run preview
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://food-delivery-backend-meux.onrender.com
