services:
  - type: static_site
    name: tomato-frontend
    buildCommand: npm run build
    publishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://food-delivery-backend-meux.onrender.com
